Encoding:
  Enabled: false

Documentation:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false

ClassLength:
  Enabled: false

MethodLength:
  Enabled: false

DoubleNegation:
  Enabled: false

AllCops:
  Include:
    - "Rakefile"
  Exclude:
    - "test_app/**/*"
